# Generated by Django 5.2.8 on 2025-12-01 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=50)),
                ('topics', models.JSONField()),
                ('embeddings', models.JSONField()),
                ('timesstamp', models.DateTimeField(auto_now_add=True)),
                ('raw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data_ingestion.rawfeed')),
            ],
        ),
        migrations.CreateModel(
            name='Insights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('score', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ProcessFeedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.processfeedback')),
            ],
        ),
    ]
